---
title: "Renaming Columns in R"
author: "John Mount, [Win-Vector LLC](http://www.win-vector.com/)"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---


```{r setup, include=FALSE}
library(tint)
knitr::opts_chunk$set(tidy = FALSE)
options(htmltools.dir.version = FALSE)

library("seplyr")
sc <- sparklyr::spark_connect(version='2.2.0', 
   master = "local")
d <- dplyr::starwars %.>%
  select_se(., qc(name, height, mass, hair_color, 
                 skin_color, eye_color, birth_year, 
                 gender, homeworld, species)) %.>%
  dplyr::copy_to(sc, ., "starwars")
```

This is our (new)^["New" is why we need the dev-versions
of [`wrapr`](https://winvector.github.io/wrapr/) and [`seplyr`](https://winvector.github.io/seplyr/).] favorite way to bulk rename columns in [`R`](https://www.r-project.org),
especially when using [`sparklyr`](https://spark.rstudio.com) to work with big data. 

There are, of course, many other ways to do this.

Consider the following data:

```{r show1}
print(d)
```

Suppose (for no reason at all) we want all columns with under-bars to be in upper case.

This is easy to achieve:

```{r rename1}
library("seplyr")
# requires dev-version at least 1.0.1
packageVersion("wrapr") 
# requires dev-version at least 0.1.6
packageVersion("seplyr") 

# find columns matching our condition
colsToRename <- grepdf(".*_.*", d)
print(colsToRename)

# build the right to left (NEW := old) assignment
mapping <- toupper(colsToRename) := colsToRename
print(mapping)

# apply the transform
d %.>% 
  rename_se(., mapping) %.>%
  head(.) %.>%
  knitr::kable(.)
```

 
```{r cleanup, include=FALSE}
sparklyr::spark_disconnect(sc)
```

